server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: https://restapitest.cfapps.io
          predicates:
            - Path=/myDefaultBook
          filters:
            - RewritePath=/myDefaultBook, /defaultBook

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway