server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          ##uri: https://sumant-rest-book.cfapps.io/
          uri: lb://bookrestapi
          predicates:
            - Path=/myDefaultBook
          filters:
            - RewritePath=/myDefaultBook, /defaultBook
        - id: book_create_route
          ##uri: https://sumant-rest-book.cfapps.io/
          uri: lb://bookrestapi
          predicates:
            - Path=/createBook
          filters:
            - RewritePath=/createBook, /api/book

    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-5598ce23-af21-4e34-850a-76b027bc9d22.cfapps.io/eureka